- name: install nginx
  yum: 
    name:
      - nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600
  

- name: start nginx
  systemd:
    name: nginx
    state: started
  
- name: creation dossier html
  file:
    path: /var/www/html
    state: directory
    
- name: index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
